# Generated by Django 3.2.13 on 2023-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Handler_Team', 'Handler_Team')], default='Patient', max_length=17),
        ),
    ]
