# Generated by Django 4.1.6 on 2023-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('doctor', 'doctor'), ('patient', 'patient'), ('handler_team', 'handler_team')], default='patient', max_length=17),
        ),
    ]
